"use strict";
// auto-generated by pwa/p2js - part of Phix, see http://phix.x10.mx
//
// bsearch.e
// =========

/*global*/ function binary_search(/*object*/ needle, /*sequence*/ haystack) {
    let /*integer*/ lo = 1, 
                    hi = length(haystack), 
                    mid = lo, 
                    c = 0;
    while (lo<=hi) {
        mid = floor((lo+hi)/2);
        c = compare(needle,$subse(haystack,mid));
        if (c<0) {
            hi = mid-1;
        } else if (c>0) {
            lo = mid+1;
        } else {
            return mid; // found!
        }
    }
//  if c>0 then
//      mid += 1
//  end if
    mid += c>0;
    return -mid;        // where it would go, if inserted now
}
