// auto-generated by pwa/p2js, see http://phix.x10.mx
"use strict";
//
// bsearch.e
// =========
//
/*without debug*/ //global function binary_search(object needle, sequence haystack)
//global function binary_search(object needle, sequence haystack, integer lo=1, hi=length(haystack), fn=0)
/*global*/ function binary_search(/*object*/ needle, /*sequence*/ haystack, /*integer*/ lo=1, hi=-1, fn=0) {
//  integer lo = 1,
//          hi = length(haystack),
//          mid = lo,
    if (hi===-1) { hi = length(haystack); }
    let /*integer*/ mid = lo, 
                    c = 0;
    while (lo<=hi) {
        mid = floor((lo+hi)/2);
        if (fn===0) {
            c = compare(needle,$subse(haystack,mid));
            if (c<0) {
                hi = mid-1;
            } else if (c>0) {
                lo = mid+1;
            } else {
                return mid; // found!
            }
        } else {
            c = fn(needle,$subse(haystack,mid));
            if (c) {
                lo = mid+1;
            } else {
                hi = mid-1;
            }
            if (lo>hi) { break; }
        }
    }
//  if c>0 then
//      mid += 1
//  end if
    mid += c>0;
    return -mid;        // where it would go, if inserted now
}
