"use strict";
// auto-generated by pwa/p2js.
//
// bsearch.e
// =========
/*global*/ function binary_search(/*object*/ needle, /*sequence*/ haystack) {
    let /*integer*/ lo = 1, 
                    hi = length(haystack), 
                    mid = lo, 
                    c = 0;
    while (compare(lo,hi)<=0) {
        mid = floor((lo+hi)/2);
        c = compare(needle,$subse(haystack,mid));
        if (compare(c,0)<0) {
            hi = mid-1;
        } else if (compare(c,0)>0) {
            lo = mid+1;
        } else {
            return mid; // found!
        }
    }
//  if c>0 then
//      mid += 1
//  end if
    mid += compare(c,0)>0;
    return -mid;        // where it would go, if inserted now
}

