"use strict";
// auto-generated by pwa/p2js - part of Phix, see http://phix.x10.mx
//
// log10.e
//

/*global*/ function log10(/*atom*/ n) {
    return log(n)*INVLN10;
}

/*global*/ function log2(/*atom*/ n) {
//  return log(n) * INVLN2
    return log(n)*1.44269504088896340739;
}
