// auto-generated by pwa/p2js, see http://phix.x10.mx
"use strict";
//
// ptagset.e
//
//  Phix implementation of tagset (auto include)
//
/*global*/ function tagset(/*integer*/ lim, start=1, step=1) {
//
// When passed a single parameter, returns a sequence of integers: {1,..,lim}.
// See the manual for other uses/examples.
//
    let /*bool*/ bString = ((start>=0X20 && start<=0X7E) && lim>=0X20) && lim<=0X7E;
    let /*integer*/ l = max(0,floor(((lim-start)+step)/step));
    let /*sequence*/ res = repeat(((bString) ? 0X20 : 0),l);
    for (let i=1, i$lim=l; i<=i$lim; i+=1) {
        res = $repe(res,i,start);
        start += step;
    }
    return res;
}

/*global*/ function tagstart(/*integer*/ start, len, step=1) {
//
// Sometimes you don't know or really care where it ends, 
// for instance tagstart('A',5) is "ABCDE", and sometimes
// tagstart(1,26) is just more natural than tagset(26,1).
//
    return tagset(start+(len-1)*step,start,step);
}
