"use strict";
// auto-generated by pwa/p2js - part of Phix, see http://phix.x10.mx
//
// ptagset.e
//
//  Phix implementation of tagset (auto include)
//
/*global*/ function tagset(/*integer*/ lim, start=1, step=1) {
//
// When passed a single parameter, returns a sequence of integers: {1,..,lim}.
// See the manual for other uses/examples.
//
    let /*bool*/ bString = ((start>=0X20 && start<=0X7E) && lim>=0X20) && lim<=0X7E;
    let /*integer*/ z = ((bString) ? 0X20 : 0), 
                    l = max(0,floor(((lim-start)+step)/step));
    let /*sequence*/ res = repeat(z,l);
    for (let i=1, i$lim=l; i<=i$lim; i+=1) {
        res = $repe(res,i,start);
        start += step;
    }
    return res;
}
