// auto-generated by pwa/p2js, see http://phix.x10.mx
"use strict";
//
// shuffle.e
//
//  Phix implementation of shuffle (auto-include)
//

/*global*/ function shuffle(/*sequence*/ s) {
// 1963 shuffle algorithm written by L.E. Moses and R.V. Oakford
//p2js:
    s = deep_copy(s);
    for (let i=length(s); i>=2; i-=1) {
        let /*integer*/ j = rand(i);
//p2js: (not permitted on strings, aka "p2js violation: JavaScript does not support string subscript destructuring")
//      {s[i],s[j]} = {s[j],s[i]}
        let /*object*/ si = $subse(s,i);
        s = $repe(s,i,$subse(s,j));
        s = $repe(s,j,si);
    }
    return s;
}
