--
-- p2js_keywords.e (nb automatically over-written, all comments get trashed)
--
-- clash detection (no single-character symbol should ever match any ttidx):
--
--   `!` = 33, `"` = 34, `#` = 35, `$` = 36, `%` = 37, `&` = 38, `'` = 39, `(` = 40, `)` = 41, `*` = 42,
--   `+` = 43, `,` = 44, `-` = 45, `.` = 46, `/` = 47, `:` = 58, `;` = 59, `<` = 60, `=` = 61, `>` = 62,
--   `?` = 63, `[` = 91, `\` = 92, `]` = 93, ``` = 96, `{` = 123, `|` = 124, `}` = 125, `~` = 126
--
global constant p2js_keywords = {
    {"integer",         T_integer           := 28},
    {"atom",            T_atom              := 48},
    {"string",          T_string            := 76},
    {"sequence",        T_sequence          := 108},
    {"object",          T_object            := 136},
    {"and",             T_and               := 148},
    {"append",          T_append            := 172},
    {"bool",            T_bool              := 192},
    {"break",           T_break             := 212},
    {"by",              T_by                := 220},
    {"case",            T_case              := 240},
    {"constant",        T_constant          := 272},
    {"default",         T_default           := 304},
    {"do",              T_do                := 312},
    {"else",            T_else              := 332},
    {"elsif",           T_elsif             := 344},
    {"end",             T_end               := 356},
    {"enum",            T_enum              := 368},
    {"exit",            T_exit              := 384},
    {"fallthru",        T_fallthru          := 420},
    {"fallthrough",     T_fallthrough       := 440},
    {"for",             T_for               := 452},
    {"forward",         T_forward           := 472},
    {"function",        T_function          := 504},
    {"global",          T_global            := 532},
    {"if",              T_if                := 540},
    {"iff",             T_iff               := 548},
    {"iif",             T_iif               := 560},
    {"include",         T_include           := 584},
    {"int",             T_int               := 588},
    {"new",             T_new               := 604},
    {"not",             T_not               := 616},
    {"nullable_string", T_nullable_string   := 676},
    {"or",              T_or                := 684},
    {"platform",        T_platform          := 720},
    {"prepend",         T_prepend           := 748},
    {"procedure",       T_procedure         := 780},
    {"repeat",          T_repeat            := 808},
    {"return",          T_return            := 828},
    {"rfind",           T_rfind             := 848},
    {"static",          T_static            := 868},
    {"switch",          T_switch            := 892},
    {"then",            T_then              := 912},
    {"to",              T_to                := 920},
    {"type",            T_type              := 936},
    {"while",           T_while             := 960},
    {"with",            T_with              := 976},
    {"without",         T_without           := 992},
    {"xor",             T_xor               := 1008},
    {"Ihandle",         T_Ihandle           := 1040},
    {"Ihandln",         T_Ihandln           := 1048},
    {"WEB",             T_WEB               := 1064},
    {"JS",              T_JS                := 1076},
    {"JAVASCRIPT",      T_JAVASCRIPT        := 1116},
    {"concat",          T_concat            := 1132},
    {"const",           T_const             := 1136},
    {"let",             T_let               := 1152}}
