--
-- p2js_depend.e (nb automatically over-written in/by p2js_scope.e, all comments get trashed)
--
-- Each entry is {"builtin.e",{dependencies, if any},{locals, if any},{{routine,{args}}}} 
-- Rebuild builtins (Ctrl R) verifies no locals clash, and renames them with a $-prefix.
-- Note "theGUI.e"/"pGUI.e"/"mpfr.e"/"timedate.e" are manually maintained, rest auto-built,
-- though you do (usually) have to kick things off with a suitable empty entry, I think.
--
global sequence p2js_depend = 
{{`assert.e`,
  {{}},
  {{}},
  {{`assert`, {{`condition`, `?`}, {`msg`, `""`}, {`args`, `{}`}, {`nFrames`, `1`}}},
   {`asserteq`, {{`a`, `?`}, {`b`, `?`}, {`msg`, `""`}, {`args`, `{}`}, {`nFrames`, `1`}}}}},
 {`base64.e`,
  {{`pflatten.e`, `substitute.e`}},
  {{`base64_init`, `aleph`, `ccha`, `init_base64`}},
  {{`decode_base64`, {{`src`, `?`}}},
   {`encode_base64`, {{`src`, `?`}, {`wrap_column`, `0`}}}}},
 {`bsearch.e`,
  {{`pmaths.e`}},
  {{`binary_index`}},
  {{`binary_search`, {{`needle`, `?`}, {`haystack`, `?`}, {`lo`, `1`}, {`hi`, `-1`}, {`fn`, `0`}}}}},
 {`dict.e`,
  {{`pmaths.e`}},
  {{`KEY`, `DATA`, `LEFT`, `HEIGHT`, `RIGHT`, `trees`, `treenames`, `roots`, `sizes`, `defaults`, `freelists`, `free_trees`,
    `init_dict`, `dict_init`, `dictionary`, `check_tid`, `newNode`, `height`, `setHeight`, `rotate`, `getBalance`, `insertNode`,
    `getNode`, `getKey`, `minValueNode`, `deleteNode`, `traverse`, `traverse_key`, `traverser`, `peekpop`}},
  {{`deld`, {{`key`, `?`}, {`tid`, `1`}}},
   {`destroy_dict`, {{`tid`, `?`}, {`justclear`, `false`}}},
   {`destroy_dictf`, {{`tid`, `?`}}},
   {`dict_name`, {{`tid`, `1`}}},
   {`dict_size`, {{`tid`, `1`}}},
   {`getd`, {{`key`, `?`}, {`tid`, `1`}, {`nullify`, `false`}}},
   {`getdd`, {{`key`, `?`}, {`dflt`, `?`}, {`tid`, `1`}, {`nullify`, `false`}}},
   {`getd_all_keys`, {{`tid`, `1`}, {`bKeys`, `true`}}},
   {`getd_by_index`, {{`node`, `?`}, {`tid`, `1`}, {`nullify`, `false`}}},
   {`getd_index`, {{`key`, `?`}, {`tid`, `1`}}},
   {`getd_partial_key`, {{`pkey`, `?`}, {`tid`, `1`}, {`rev`, `false`}}},
   {`is_dict`, {{`tid`, `?`}}},
   {`named_dict`, {{`name`, `?`}}},
   {`new_dict`, {{`kd_pairs`, `{}`}, {`pool_only`, `0`}}},
   {`new_dicts`, {{`n`, `?`}}},
   {`peep_dict`, {{`tid`, `1`}, {`rev`, `false`}}},
   {`pop_dict`, {{`tid`, `1`}, {`rev`, `false`}}},
   {`setd`, {{`key`, `?`}, {`data`, `?`}, {`tid`, `1`}}},
   {`setd_default`, {{`o`, `?`}, {`tid`, `?`}}},
   {`traverse_dict`, {{`rid`, `?`}, {`user_data`, `0`}, {`tid`, `1`}, {`rev`, `false`}}},
   {`traverse_dict_partial_key`, {{`rid`, `?`}, {`pkey`, `?`}, {`user_data`, `0`}, {`tid`, `1`}, {`rev`, `false`}}}}},
 {`factorial.e`,
  {{`pmaths.e`}},
  {{`finit`, `fcache`, `gamma`}},
  {{`choose`, {{`n`, `?`}, {`k`, `?`}}},
   {`factorial`, {{`n`, `?`}}},
   {`k_perm`, {{`n`, `?`}, {`k`, `?`}}}}},
 {`file_utils.e`,
  {{`find.e`, `pcase.e`, `pmaths.e`}},
  {{}},
  {{`file_size_k`, {{`size`, `?`}, {`width`, `1`}}},
   {`get_file_base`, {{`path`, `?`}}},
   {`get_file_extension`, {{`filename`, `?`}}},
   {`get_file_name`, {{`path`, `?`}}},
   {`get_file_name_and_path`, {{`filepath`, `?`}, {`dropslash`, `true`}}},
   {`get_file_path`, {{`path`, `?`}, {`dropslash`, `true`}}},
   {`get_file_path_and_name`, {{`filepath`, `?`}, {`dropslash`, `true`}}}}},
 {`find.e`,
  {{}},
  {{}},
  {{`find`, {{`needle`, `?`}, {`haystack`, `?`}, {`start`, `1`}}},
   {`rfind`, {{`needle`, `?`}, {`haystack`, `?`}, {`start`, `-1`}}}}},
 {`findrepl.e`,
  {{`find.e`}},
  {{}},
  {{`find_replace`, {{`needle`, `?`}, {`haystack`, `?`}, {`replacement`, `?`}, {`max_replacements`, `0`}}}}},
 {`gcd.e`,
  {{`pmaths.e`}},
  {{`pinit`, `fact`, `totient`}},
  {{`gcd`, {{`u`, `?`}, {`v`, `0`}}},
   {`lcm`, {{`m`, `?`}, {`n`, `0`}}},
   {`phi`, {{`n`, `?`}}}}},
 {`glmath.e`,
  {{}},
  {{}},
  {}},
 {`log10.e`,
  {{}},
  {{}},
  {{`log10`, {{`n`, `?`}}},
   {`log2`, {{`n`, `?`}}}}},
 {`match.e`,
  {{`find.e`, `match.e`, `pcase.e`, `pfindall.e`}},
  {{`ends`}},
  {{`begins`, {{`sub_text`, `?`}, {`full_text`, `?`}, {`start`, `1`}}},
   {`match`, {{`needle`, `?`}, {`haystack`, `?`}, {`start`, `1`}, {`case_sensitive`, `true`}}},
   {`match_all`, {{`needle`, `?`}, {`haystack`, `?`}, {`start`, `1`}, {`case_sensitive`, `true`}, {`overlap`, `false`}}},
   {`rmatch`, {{`needle`, `?`}, {`haystack`, `?`}, {`endx`, `length(haystack)`}, {`case_sensitive`, `true`}}},
   {`ends`, {{`sub_text`, `?`}, {`full_text`, `?`}, {`endx`, `-1`}}}}},
 {`matchrepl.e`,
  {{`match.e`}},
  {{}},
  {{`match_replace`, {{`needle`, `?`}, {`haystack`, `?`}, {`replacement`, `?`}, {`maxr`, `0`}}}}},
 {`misc.e`,
  {{`pmaths.e`}},
  {{`trig_range`}},
  {{`arccos`, {{`x`, `?`}}},
   {`arcsin`, {{`x`, `?`}}},
   {`reverse`, {{`s`, `?`}}}}},
 {`mpfr.e`,
  {{`find.e`, `pmaths.e`, `primes.e`, `ptagset.e`, `match.e`, `substitute.e`, `mpfr.e`}},
  {{}},
  {{`mpz_get_short_str`, {{`op`, `?`}, {`ml`, `20`}, {`base`, `10`}, {`comma_fill`, `false`}, {`what`, `digits`}}},
   {`mpz_get_str`, {{`x`, `?`}, {`base`, `10`}, {`comma_fill`, `false`}}},
   {`mpfr_get_fixed`, {{`x`, `?`}, {`dp`, `6`}, {`base`, `10`}, {`comma_fill`, `false`}, {`maxlen`, `0`}}}}},
 {`ordinal.e`,
  {{`find.e`, `ordinal.e`, `pcolumn.e`, `pmaths.e`}},
  {{`oinit`, `twenties`, `decades`, `orders`, `irregs`, `ordinals`, `inito`, `twenty`, `decade`, `hundred`, `thousand`, `triplet`,
    `spell`}},
  {{`ord`, {{`n`, `?`}}},
   {`ordinal`, {{`n`, `?`}, {`bJustSpell`, `false`}}},
   {`ordinant`, {{`n`, `?`}}}}},
 {`pApply.e`,
  {{}},
  {{`apply_`}},
  {{`apply`, {{`s`, `?`}, {`fn`, `?`}, {`userdata`, `{}`}}},
   {`papply`, {{`s`, `?`}, {`fn`, `?`}, {`userdata`, `{}`}}}}},
 {`pcase.e`,
  {{`find.e`, `pApply.e`, `pcase.e`}},
  {{`caseinit`, `toUpper`, `toLower`, `str_methods`, `LOWER`, `UPPER`, `CAPITALISE`, `SENTENCE`, `INVERT`, `initcase`,
    `proper_nouns`}},
  {{`islower`, {{`ch`, `?`}}},
   {`isupper`, {{`ch`, `?`}}},
   {`lower`, {{`x`, `?`}}},
   {`proper`, {{`s`, `?`}, {`method`, `"CAPITALISE"`}}},
   {`upper`, {{`x`, `?`}}}}},
 {`pcolumn.e`,
  {{`ptagset.e`}},
  {{}},
  {{`columnize`, {{`source`, `?`}, {`columns`, `{}`}, {`defval`, `0`}}}}},
 {`pdates.e`,
  {{}},
  {{`dot`, `dim`, `t`, `days`, `dinit`, `initd`}},
  {{`day_of_week`, {{`y`, `?`}, {`m`, `0`}, {`d`, `0`}, {`bAsText`, `false`}}},
   {`day_of_year`, {{`y`, `?`}, {`m`, `0`}, {`d`, `0`}}},
   {`days_in_month`, {{`y`, `?`}, {`m`, `0`}}},
   {`is_leap_year`, {{`y`, `?`}}},
   {`week_number`, {{`y`, `?`}, {`m`, `0`}, {`d`, `0`}}}}},
 {`pdecodeflags.e`,
  {{}},
  {{}},
  {{`decode_flags`, {{`FlagSet`, `?`}, {`v`, `?`}, {`sep`, `"+"`}}}}},
 {`pelapsed.e`,
  {{`match.e`, `pmaths.e`}},
  {{`elaps`, `elapsdwy`}},
  {{`elapsed`, {{`s`, `?`}, {`min_s`, `0`}, {`fmt`, `""`}}},
   {`elapsed_short`, {{`s`, `?`}, {`min_s`, `0`}, {`fmt`, `""`}}}}},
 {`permute.e`,
  {{`factorial.e`, `pextract.e`, `ptagset.e`, `punique.e`, `sort.e`}},
  {{`combos`, `rep_combos`}},
  {{`combinations`, {{`s`, `?`}, {`k`, `?`}}},
   {`combinations_with_repetitions`, {{`s`, `?`}, {`k`, `-1`}}},
   {`permute`, {{`n`, `?`}, {`s`, `?`}, {`bFast`, `false`}}},
   {`permutes`, {{`s`, `?`}, {`cb`, `0`}, {`k`, `length(s)`}}}}},
 {`pextract.e`,
  {{`pmaths.e`, `ptagset.e`}},
  {{}},
  {{`extract`, {{`source`, `?`}, {`indexes`, `?`}, {`invert`, `false`}}},
   {`reinstate`, {{`source`, `?`}, {`indexes`, `?`}, {`replacements`, `?`}, {`invert`, `false`}}}}},
 {`pfactors.e`,
  {{`find.e`, `pfactors.e`, `pmaths.e`, `primes.e`, `sort.e`}},
  {{`lim_chk`, `check_limits`}},
  {{`factors`, {{`n`, `?`}, {`include1`, `0`}}},
   {`factor_count`, {{`n`, `?`}}},
   {`factor_sum`, {{`n`, `?`}}},
   {`prime_factors`, {{`n`, `?`}, {`duplicates`, `false`}, {`maxprime`, `100`}}},
   {`prime_powers`, {{`n`, `?`}}},
   {`square_free`, {{`n`, `?`}, {`maxprime`, `100`}}}}},
 {`pFilter.e`,
  {{`find.e`, `pFilter.e`, `pmaths.e`}},
  {{}},
  {{`filter`, {{`s`, `?`}, {`rs`, `?`}, {`userdata`, `{}`}, {`rangetype`, `""`}}},
   {`filter_count`, {{`s`, `?`}, {`rs`, `?`}, {`userdata`, `{}`}, {`rangetype`, `""`}}}}},
 {`pfindall.e`,
  {{`find.e`}},
  {{}},
  {{`find_all`, {{`needle`, `?`}, {`haystack`, `?`}, {`start`, `1`}}}}},
 {`pfindany.e`,
  {{`find.e`, `match.e`}},
  {{`match_any`}},
  {{`find_any`, {{`needles`, `?`}, {`haystack`, `?`}, {`start`, `1`}, {`mult`, `1`}}},
   {`match_any`, {{`needles`, `?`}, {`haystack`, `?`}, {`start`, `1`}, {`mult`, `1`}}}}},
 {`pflatten.e`,
  {{`find.e`, `pflatten.e`}},
  {{}},
  {{`flatten`, {{`s`, `?`}, {`res`, `""`}}},
   {`join`, {{`s`, `?`}, {`delim`, `0X20`}, {`lastdelim`, `delim`}, {`fmt`, `""`}}},
   {`join_by`, {{`s`, `?`}, {`step`, `?`}, {`n`, `?`}, {`step_pad`, `"   "`}, {`n_pad`, `"\n"`}, {`fmt`, `""`}, {`skip`, `0`}}},
   {`join_path`, {{`path_elements`, `?`}, {`trailsep`, `0`}}}}},
 {`pGUI.e`,
  {{}},
  {{}},
  {{`crash`, {{`msg`, `?`}, {`args`, `{}`}, {`nFrames`, `1`}}},
   {`IupMessage`, {{`title`, `NULL`}, {`msg`, `NULL`}, {`args`, `{}`}, {`bWrap`, `true`}}},
   {`IupTableSetData`, {{`table`, `?`}, {`data`, `?`}, {`bReset`, `true`}}},
   {`IupTimer`, {{`func`, `NULL`}, {`msecs`, `0`}, {`active`, `true`}}}}},
 {`theGUI.e`,
  {{`bsearch.e`, `dict.e`, `find.e`, `match.e`, `misc.e`, `pApply.e`, `pFilter.e`, `pcase.e`, `pcolumn.e`, `pdates.e`,
    `pdecodeflags.e`, `pextract.e`, `pfindany.e`, `pflatten.e`, `pmaths.e`, `porall.e`, `psplit.e`, `psqop.e`, `psum.e`,
    `ptagset.e`, `ptrim.e`, `scanf.e`, `sort.e`, `substitute.e`, `to_int.e`, `vslice.e`}},
  {{`COPYRIGHT`, `run_unit_tests`, `bInit`, `bDiagnostics`, `UNDEFINED`, `PrimaryWindowID`, `handlers`, `handler_sigs`,
    `leaf_only`, `backend`, `control_set`, `DIALOG`, `BOX`, `CANVAS`, `BUTTON`, `CALENDAR`, `CHECKBOX`, `DATEPICK`, `DROPDOWN`,
    `GRAPH`, `LABEL`, `LIST`, `MENU`, `PROGRESS`, `SLIDER`, `SPIN`, `TABS`, `TABLE`, `TEXT`, `TREE`, `TIMER`, `lcs`, `ctrl_names`,
    `cf_glags`, `CF_EXPANDB`, `CF_EXPANDH`, `CF_EXPANDV`, `CF_CANFOCUS`, `CF_SCROLLBARS`, `CF_CANVAS`, `CF_CONTAINER`,
    `CF_VERTICAL`, `CF_RESIZE`, `CF_MODAL`, `CF_SPLIT`, `CF_CONCRETE`, `CF_SCROLLFIX`, `CF_SCROLLFIX3`, `CF_TRACKLEAVE`,
    `CF_INVISIBLE`, `CF_INACTIVE`, `CF_POPUP`, `CF_CLOSE_ON_ESC`, `CF_EXPAND`, `CF_HEXPAND`, `CF_VEXPAND`, `ctrl_set_attr`,
    `ctrl_get_attr`, `ctrl_handles`, `ctrl_images`, `ctrl_types`, `ctrl_hdc`, `ctrl_flags`, `ctrl_parent`, `children_ids`,
    `ctrl_titles`, `tool_tips`, `ctrl_size`, `ctrl_font`, `ctrl_fonts`, `ctrl_bg`, `ctrl_fg`, `ctrl_penwidth`, `ctrl_penstyle`,
    `ctrl_xtra`, `ctrl_sbinfo`, `ctrl_cursors`, `user_data`, `deferred_attr`, `clear_tables`, `SZ_MARGIN`, `SZ_W`, `SZ_H`,
    `SZ_NORMAL_W`, `SZ_NORMAL_H`, `SZ_USER_W`, `SZ_USER_H`, `SZ_MIN_W`, `SZ_MIN_H`, `SZ_MAX_W`, `SZ_MAX_H`, `SZ_X`, `SZ_Y`,
    `SZ_LENGTH`, `DX_CANVAS`, `DX_LAST_FOCUS`, `DX_LAST_MOUSE`, `DX_CAPTURE`, `DX_DEF_ENTER`, `DX_DEF_ESCAPE`, `DX_FULLSCREEN`,
    `DX_WAS_MAXIMISED`, `DX_GTK_STATE`, `DX_NOTITLE`, `DX_ACTIVEPOP`, `DX_DLG_LEN`, `CX_BOX_GAP`, `CX_BOX_SPACE_H`,
    `CX_BOX_SPACE_V`, `SB_HVISB`, `SB_VVISB`, `SB_VTTOP`, `SB_VTEND`, `SB_HTLFT`, `SB_HTEND`, `SB_TIMER`, `SB_CLIKX`, `SB_CLIKY`,
    `SB_DRAGG`, `SB_MONLD`, `SB_CKMON`, `SB_VWIDE`, `SB_HHIGH`, `SB_SCRLW`, `SB_SCRLH`, `SB_ORIGX`, `SB_ORIGY`, `SB_INFOLEN`,
    `btn_attrs`, `CXBTN_IMAGE`, `CXBTN_HOV`, `CXBTN_UHT`, `CXBTN_LEN`, `chk_attrs`, `CXCHK_RADIO`, `CXCHK_VALUE`, `CXCHK_LEN`,
    `calendar_attrs`, `CXCAL_RANGE`, `CXCAL_BGSEL`, `CXCAL_BGHOV`, `CXCAL_BGHBX`, `CXCAL_YEAR`, `CXCAL_MONTH`, `CXCAL_DAY`,
    `CXCAL_PREV`, `CXCAL_LAST`, `CXCAL_LHOV`, `CXCAL_RHOV`, `CXCAL_STATE`, `CXCAL_LOHOV`, `CXCAL_HIHOV`, `CXCAL_HOV`, `CXCAL_SEL`,
    `CXCAL_DT_PICK`, `CXCAL_LEN`, `TG_MONTH`, `TG_YEAR`, `TG_DECADE`, `TG_CENTURY`, `TG_MILLEN`, `graph_attrs`, `GX_GRID`,
    `GX_GRIDCLR`, `GX_GTITLE`, `GX_XNAME`, `GX_YNAME`, `GX_LEGEND`, `GX_LEGENDBOX`, `GX_LEGENDPOS`, `GX_LEGENDXY`, `GX_MODE`,
    `GX_BARMODE`, `GX_MARKSTYLE`, `GX_MARKSIZE`, `GX_XMIN`, `GX_XMAX`, `GX_YMIN`, `GX_YMAX`, `GX_XMARGIN`, `GX_YMARGIN`,
    `GX_XYSHIFT`, `GX_YXSHIFT`, `GX_XANGLE`, `GX_YANGLE`, `GX_XACROSS`, `GX_YACROSS`, `GX_XTICK`, `GX_YTICK`, `GX_XTICKFMT`,
    `GX_YTICKFMT`, `GX_LEN`, `grph_attr_types`, `grph_attr_names`, `lbl_attrs`, `CXLBL_ALIGN`, `CXLBL_LEN`, `list_attrs`,
    `LX_BGSEL`, `LX_BGHOV`, `LX_CARET`, `LX_CARETCLR`, `LX_CARETIME`, `LX_CARETEND`, `LX_CARETIMER`, `LX_CURSORX`, `LX_CURSORY`,
    `LX_DATA`, `LX_LINEHT`, `LX_LINESPP`, `LX_CHARWID`, `LX_N_ROWS`, `LX_LONGEST`, `LX_HOVLINE`, `LX_MULTIPLE`, `LX_SELECTED`,
    `LX_SSTART`, `LX_SHOWLINE`, `LX_TOPLINE`, `LX_LEN`, `list_attr_types`, `list_attr_names`, `CX_MENUS`, `CX_MEXTRA`,
    `CX_MENU_LEN`, `MX_ITEMS`, `MX_PARENT`, `MX_TEXT`, `MX_SUBMENU`, `MX_IMAGE`, `MX_ENABLED`, `MX_ID`, `MX_CHECKED`, `MX_WIDTH`,
    `MX_HEIGHT`, `MX_KEYMODE`, `MX_HOT`, `MX_SEL`, `MX_OWNER`, `MX_POPUP`, `MX_WIDGET`, `MX_X`, `MX_Y`, `MX_TGTIMG`, `MX_WIDTHS`,
    `TG_CONTIGUOUS`, `TG_POPMENU_BGCLR`, `TG_MENUBAR_BGCLR`, `TG_MENUHOV_BGCLR`, `TG_MBARHOV_FGCLR`, `TG_MENUHOV_FGCLR`,
    `TG_MENUSEP_FGCLR`, `bMenuNorm`, `draw_menu`, `progress_attrs`, `CX_PROGRESS_IMAGE`, `CX_PROGRESS_DRIFT`, `CX_PROGRESS_TIMER`,
    `CX_PROGRESS_VALUE`, `CX_PROGRESS_START`, `CX_PROGRESS_LIMIT`, `CX_PROGRESS_LEN`, `slider_attrs`, `CX_SLIDER_HORIZ`,
    `CX_SLIDER_VALUE`, `CX_SLIDER_MINMAX`, `CX_SLIDER_ONTHUMB`, `CX_SLIDER_DRAGG`, `CX_SLIDER_DRAGXY`, `CX_SLIDER_LEN`,
    `split_attrs`, `CX_SPLIT_DRAGG`, `CX_SPLIT_DRAGXY`, `CX_SPLIT_LEN`, `table_attrs`, `CXTBL_BGSEL`, `CXTBL_BGHOV`,
    `CXTBL_COLUMNS`, `CXTBL_COLDRAG`, `CXTBL_DRAGTITLE`, `CXTBL_COLSIZE`, `CXTBL_RESIZEHOV`, `CXTBL_RCX`, `CXTBL_COLSORT`,
    `CXTBL_SORTCOLS`, `CXTBL_TAGSET`, `CXTBL_INVTAG`, `CXTBL_DATA`, `CXTBL_HOVCOL`, `CXTBL_HOVLINE`, `CXTBL_TOPLINE`,
    `CXTBL_LINEHT`, `CXTBL_LINESPP`, `CXTBL_RESIZESINK`, `CXTBL_N_ROWS`, `CXTBL_SELMODE`, `CXTBL_SELECTED`, `CXTBL_SSTART`,
    `CXTBL_CURSORY`, `CXTBL_CURSORX`, `CXTBL_ACTCOLS`, `CXTBL_LEN`, `tab_attrs`, `CXTAB_ITEMS`, `CXTAB_CLOSE`, `CXTAB_SEL`,
    `CXTAB_1ST`, `CXTAB_BUMP`, `CXTAB_ROVER`, `CXTAB_TWSAVE`, `CXTAB_LEN`, `text_attrs`, `CXTEXT_CARETCLR`, `CXTEXT_CARETCT`,
    `CXTEXT_CARETIME`, `CXTEXT_CARETIMER`, `CXTEXT_CARETPOS`, `CXTEXT_CHARSFROM`, `CXTEXT_LASTW`, `CXTEXT_RICONW`,
    `CXTEXT_HADFOCUS`, `CXTEXT_SELSTART`, `CXTEXT_VALUE`, `CXTEXT_CUEBANNER`, `CXTEXT_UNDO`, `CXTEXT_UNDOPOS`, `CXTEXT_KEYLOG`,
    `CXTEXT_KLOGPOS`, `CXTEXT_SDD`, `CXSPIN_HOV`, `CXTEXT_LEN`, `text_attr_names`, `tree_attrs`, `CXTREE_BGSEL`, `CXTREE_BGHOV`,
    `CXTREE_FGSEL`, `CXTREE_SELFULL`, `CXTREE_LINESTEP`, `CXTREE_HOVLINE`, `CXTREE_HOVCOL`, `CXTREE_CHECKED`, `CXTREE_DATA`,
    `CXTREE_IMAGE`, `CXTREE_SELECTED`, `CXTREE_TOPITEM`, `CXTREE_LEN`, `tree_attr_types`, `tree_attr_names`, `tg_bad_attr`,
    `TG_IMG_HANDLE`, `TG_IMG_TRANSPARENT`, `TG_IMG_PIXEL_MEM`, `TG_IMG_WIDTH`, `TG_IMG_HEIGHT`, `TG_IMG_NEXT`, `TG_IMG_BGCLR`,
    `TG_IMG_FGCLR`, `TG_IMG_DRAW_FONT`, `TG_IMG_LINESTYLE`, `TG_IMG_LINEWIDTH`, `TG_IMG_USER_DATA`, `TG_IMG_LAYOUT`,
    `TG_IMG_CLIP`, `TG_IMG_SIZE`, `gimages`, `gimgrey`, `gi_freelist`, `gpixbufs`, `pixbuf_xtra`, `TG_PB_BGCLR`, `TG_PB_FGCLR`,
    `TG_PB_LINESTYLE`, `TG_PB_LINEWIDTH`, `TG_PB_USER_DATA`, `gpb_freelist`, `gcps`, `gcx`, `gcxs`, `last_xpgui_rid`, `rtnn`,
    `nnatom`, `LOWORD`, `HIWORD`, `tg_get_sig`, `tg_add_control`, `tg_set_ctrl_flag`, `tg_raw_string_ptr`, `tg_word_array`,
    `tg_double_array`, `VK_XSHIFT`, `VK_XCTRL`, `VK_XALT`, `key_mappings`, `VK_TAB`, `VK_LF`, `VK_RSHIFT`, `VK_LALT`, `VK_RALT`,
    `VK_LWIN`, `VK_RWIN`, `VK_ESC`, `VK_CAPSLOCK`, `VK_NUMLOCK`, `VK_PAUSE`, `VK_SCROLL`, `VK_APPS`, `VK_F12`, `known_colours`,
    `TG_DARK_CYAN`, `TG_DARK_VIOLET`, `TG_MAROON`, `known_colour_names`, `known_colour_values`, `box_spacing`, `TG_SPACE_NONE`,
    `TG_SPACE_LEFT`, `TG_SPACE_TOP`, `TG_SPACE_RIGHT`, `TG_SPACE_BOTTOM`, `TG_SPACE_BETWEEN`, `TG_SPACE_AROUND`,
    `TG_SPACE_CENTRE`, `box_spacing_descs`, `box_spacing_masks`, `TG_STD_FONT`, `TG_UNDERLINE`, `TG_STRIKEOUT`, `TG_SQUIGGLE`,
    `TG_CURRENT`, `TG_LEFT`, `TG_RIGHT`, `TG_MOUSEPOS`, `TG_LEFTPARENT`, `TG_RIGHTPARENT`, `TG_TOP`, `TG_TOPPARENT`, `TG_BOTTOM`,
    `TG_BOTTOMPARENT`, `TG_PARENT`, `gGetAlignName`, `dashers`, `tg_get_box_spacing_name`, `M_CTRL`, `M_SHIFT`, `M_ALT`,
    `M_NOT_KEY`, `gMenuCcsa`, `gGetColourName`, `tg_get_colour_value`, `C_DBL`, `CAIRO_ANTIALIAS_NONE`, `CAIRO_FORMAT_ARGB32`,
    `GDK_INTERP_NEAREST`, `GDK_POINTER_MOTION_MASK`, `GDK_BUTTON_PRESS_MASK`, `GDK_BUTTON_RELEASE_MASK`, `GDK_KEY_PRESS_MASK`,
    `GDK_LEAVE_NOTIFY_MASK`, `GDK_SCROLL_MASK`, `GDK_KBR_MASK`, `GDK_SHIFT_MASK`, `GDK_CONTROL_MASK`, `GDK_ALT_MASK`,
    `GDK_LEFT_MASK`, `GDK_BUTTON1_MASK`, `GDK_MIDDLE_MASK`, `GDK_RIGHT_MASK`, `GDK_TRIPLE_BUTTON_PRESS`, `GDK_LEAVE_NOTIFY`,
    `GDK_WINDOW_STATE`, `GDK_COLORSPACE_RGB`, `GDK_SELECTION_CLIPBOARD`, `GDK_HINT_MIN_SIZE`, `GDK_HINT_MAX_SIZE`, `GDK_FLEUR`,
    `GDK_SB_H_DOUBLE_ARROW`, `GDK_SB_V_DOUBLE_ARROW`, `GTK_FILE_CHOOSER_ACTION_OPEN`, `GTK_RESPONSE_ACCEPT`,
    `GTK_RESPONSE_CANCEL`, `GTK_WINDOW_TOPLEVEL`, `GTK_WINDOW_POPUP`, `GDK_WINDOW_STATE_ICONIFIED`, `GDK_WINDOW_STATE_MAXIMIZED`,
    `GDK_WINDOW_TYPE_HINT_POPUP_MENU`, `WM_USER`, `BI_RGB`, `BI_BITFIELDS`, `CF_TEXT`, `CF_DIB`, `COLOR_BTNFACE`, `CS_VREDRAW`,
    `CS_HREDRAW`, `CS_DBLCLKS`, `CS_OWNDC`, `CW_USEDEFAULT`, `DEFAULT_CHARSET`, `DIB_RGB_COLORS`, `DT_NOCLIP`,
    `ERROR_INVALID_PARAMETER`, `FW_NORMAL`, `FW_BOLD`, `GMEM_MOVEABLE`, `GMEM_DDESHARE`, `GMEM_CLIPBOARD`, `GWL_STYLE`,
    `GWL_USERDATA`, `HWND_TOPMOST`, `IDC_ARROW`, `IDC_SIZENS`, `IDC_SIZEWE`, `IDC_SIZEALL`, `LF_FACESIZE`, `LOGPIXELSY`,
    `MA_NOACTIVATE`, `MK_LBUTTON`, `MK_RBUTTON`, `MK_SHIFT`, `MK_CONTROL`, `MK_MBUTTON`, `NULL_BRUSH`, `OBJ_MEMDC`, `PM_NOREMOVE`,
    `PS_SOLID`, `PS_ALTERNATE`, `SM_CXSCREEN`, `SM_CYSCREEN`, `SRCCOPY`, `SW_HIDE`, `SW_SHOWNORMAL`, `SW_MAXIMIZE`, `SW_MINIMIZE`,
    `SW_RESTORE`, `SWP_FLAGS`, `SWP_NOSIZE`, `SWP_NOMOVE`, `SWP_NOZORDER`, `SWP_NOACTIVATE`, `SWP_FRAMECHANGED`, `SWP_NOCOPYBITS`,
    `SWP_SHOWWINDOW`, `SWP_UPDATECACHE`, `TME_CANCEL`, `TME_LEAVE`, `WA_INACTIVE`, `wm_messages`, `WM_DESTROY`, `WM_SIZE`,
    `WM_ACTIVATE`, `WM_SETFOCUS`, `WM_KILLFOCUS`, `WM_PAINT`, `WM_CLOSE`, `WM_ERASEBKGND`, `WM_SETCURSOR`, `WM_MOUSEACTIVATE`,
    `WM_GETMINMAXINFO`, `WM_NCACTIVATE`, `WM_KEYDOWN`, `WM_KEYUP`, `WM_CHAR`, `WM_SYSKEYDOWN`, `WM_SYSKEYUP`, `WM_SYSCHAR`,
    `WM_COMMAND`, `WM_SYSCOMMAND`, `WM_MOUSEMOVE`, `WM_LBUTTONDOWN`, `WM_LBUTTONUP`, `WM_LBUTTONDBLCLK`, `WM_RBUTTONDOWN`,
    `WM_RBUTTONUP`, `WM_RBUTTONDBLCLK`, `WM_MBUTTONDOWN`, `WM_MBUTTONUP`, `WM_MBUTTONDBLCLK`, `WM_MOUSEWHEEL`, `WM_XBUTTONDOWN`,
    `WM_MOUSEHWHEEL`, `WM_SIZING`, `WM_MOVING`, `WM_ENTERSIZEMOVE`, `WM_MOUSELEAVE`, `WM_MSGS`, `WM_NAMES`, `WS_CHILD`,
    `WS_POPUP`, `WS_EX_ACCEPTFILES`, `WS_EX_NOACTIVATE`, `WS_EX_TOPMOST`, `WS_BORDER`, `WS_CAPTION`, `WS_MINIMIZEBOX`,
    `WS_MAXIMIZEBOX`, `WS_OVERLAPPED`, `WS_SYSMENU`, `WS_TABSTOP`, `WS_MINMAXTHICK`, `WS_VISIBLE`, `WS_OVERLAPPEDWINDOW`,
    `TRANSPARENT`, `OPAQUE`, `tg_WinAPI_get_wm_name`, `tg_WinAPI_wm_ignorable`, `bGTK2`, `bGTK3`, `x_cairo_arc`, `x_cairo_clip`,
    `x_cairo_close_path`, `x_cairo_create`, `x_cairo_curve_to`, `x_cairo_destroy`, `x_cairo_fill`, `x_cairo_get_antialias`,
    `x_cairo_get_line_width`, `x_cairo_image_surface_create_for_data`, `x_cairo_line_to`, `x_cairo_move_to`, `x_cairo_new_path`,
    `x_cairo_paint`, `x_cairo_rectangle`, `x_cairo_reset_clip`, `x_cairo_restore`, `x_cairo_rotate`, `x_cairo_save`,
    `x_cairo_scale`, `x_cairo_set_antialias`, `x_cairo_set_dash`, `x_cairo_set_line_width`, `x_cairo_set_source_rgb`,
    `x_cairo_stroke`, `x_cairo_surface_destroy`, `x_cairo_translate`, `x_gdk_cairo_create`, `x_gdk_cairo_set_source_pixbuf`,
    `x_gdk_cursor_new_for_display`, `x_gdk_display_get_default`, `x_gdk_display_get_monitor`, `x_gdk_display_get_pointer`,
    `x_gdk_display_store_clipboard`, `x_gdk_monitor_get_geometry`, `x_gdk_pixbuf_get_has_alpha`, `x_gdk_pixbuf_composite`,
    `x_gdk_pixbuf_copy_area`, `x_gdk_pixbuf_fill`, `x_gdk_pixbuf_get_height`, `x_gdk_pixbuf_get_n_channels`,
    `x_gdk_pixbuf_get_pixels`, `x_gdk_pixbuf_get_rowstride`, `x_gdk_pixbuf_get_width`, `x_gdk_pixbuf_new`,
    `x_gdk_pixbuf_new_from_xpm_data`, `x_gdk_pixbuf_new_subpixbuf`, `x_gdk_screen_get_height`, `x_gdk_screen_get_width`,
    `x_gdk_window_get_display`, `x_gdk_window_invalidate_rect`, `x_gdk_window_process_updates`, `x_gdk_window_set_cursor`,
    `x_gtk_clipboard_clear`, `x_gtk_clipboard_get`, `x_gtk_clipboard_set_image`, `x_gtk_clipboard_set_text`,
    `x_gtk_clipboard_store`, `x_gtk_clipboard_wait_for_image`, `x_gtk_clipboard_wait_for_text`,
    `x_gtk_clipboard_wait_is_text_available`, `x_gtk_container_add`, `x_gtk_dialog_run`, `x_gtk_drawing_area_new`,
    `x_gtk_file_chooser_dialog_new`, `x_gtk_file_chooser_add_filter`, `x_gtk_file_chooser_get_filename`,
    `x_gtk_file_chooser_get_filenames`, `x_gtk_file_chooser_set_select_multiple`, `x_gtk_file_filter_new`,
    `x_gtk_file_filter_add_pattern`, `x_gtk_file_filter_set_name`, `x_gtk_grab_add`, `x_gtk_grab_remove`, `x_gtk_main`,
    `x_gtk_main_quit`, `x_gtk_widget_add_events`, `x_gtk_widget_destroy`, `x_gtk_widget_get_pointer`, `x_gtk_widget_get_visible`,
    `x_gtk_widget_get_window`, `x_gtk_widget_grab_focus`, `x_gtk_widget_hide`, `x_gtk_widget_queue_draw`, `x_gtk_widget_realize`,
    `x_gtk_widget_set_events`, `x_gtk_widget_set_size_request`, `x_gtk_widget_show`, `x_gtk_widget_show_all`,
    `x_gtk_window_deiconify`, `x_gtk_window_fullscreen`, `x_gtk_window_get_decorated`, `x_gtk_window_get_deletable`,
    `x_gtk_window_get_position`, `x_gtk_window_get_resizable`, `x_gtk_window_get_size`, `x_gtk_window_get_title`,
    `x_gtk_window_get_transient_for`, `x_gtk_window_iconify`, `x_gtk_window_maximize`, `x_gtk_window_move`, `x_gtk_window_new`,
    `x_gtk_window_resize`, `x_gtk_window_set_decorated`, `x_gtk_window_set_default_size`, `x_gtk_window_set_deletable`,
    `x_gtk_window_set_geometry_hints`, `x_gtk_window_set_modal`, `x_gtk_window_set_resizable`, `x_gtk_window_set_title`,
    `x_gtk_window_set_transient_for`, `x_gtk_window_set_type_hint`, `x_gtk_window_unfullscreen`, `x_gtk_window_unmaximize`,
    `x_g_free`, `x_g_idle_add`, `x_g_slist_free`, `x_g_signal_connect_data`, `x_g_source_remove`, `x_g_timeout_add`,
    `x_pango_cairo_create_layout`, `x_pango_cairo_show_layout`, `x_pango_font_description_from_string`,
    `x_pango_layout_get_pixel_size`, `x_pango_layout_set_font_description`, `x_pango_layout_set_markup_with_accel`,
    `x_pango_layout_set_text`, `xg_object_unref`, `idGdkEventButton`, `idGdkEventConfigure`, `idGdkEventFocus`, `idGdkEventKey`,
    `idGdkEventMotion`, `idGdkEventScroll`, `idGdkEventCrossing`, `idGdkEventWindowState`, `idGdkRectangle`, `idGdkGeometry`,
    `gtk_fleur_cursor`, `gtk_col_resize_cursor`, `gtk_row_resize_cursor`, `GTK_ID_LOOKUP`, `xCloseClipboard`, `xEmptyClipboard`,
    `xGetClipboardData`, `xGlobalAlloc`, `xGlobalFree`, `xGlobalLock`, `xGlobalSize`, `xGlobalUnlock`,
    `xIsClipboardFormatAvailable`, `xOpenClipboard`, `xSetClipboardData`, `xBeginPaint`, `xBitBlt`, `xClientToScreen`,
    `xCreateCompatibleBitmap`, `xCreateCompatibleDC`, `xCreateDIBSection`, `xCreateFontIndirect`, `xCreatePen`, `xCreateRectRgn`,
    `xExtCreatePen`, `xCreateSolidBrush`, `xCreateWindowEx`, `xDefWindowProc`, `xDeleteObject`, `xDestroyWindow`,
    `xDispatchMessage`, `xDrawText`, `xEnableWindow`, `xEndPaint`, `xFillRect`, `xFindWindow`, `xGetClientRect`, `xGetCursorPos`,
    `xGetDC`, `xGetDeviceCaps`, `xGetKeyState`, `xGetLastError`, `xGetMessage`, `xGetObjectType`, `xGetParent`, `xGetPixel`,
    `xGetStockObject`, `xGetSystemMetrics`, `xGetTextExtentPoint32`, `xGetTextExtentPoint32W`, `xGetWindowLong`,
    `xGetWindowPlacement`, `xGetWindowRect`, `xInvalidateRect`, `xValidateRect`, `xIsWindowVisible`, `xIsZoomed`, `xIsIconic`,
    `xKillTimer`, `xLineTo`, `xLoadCursor`, `xLoadIcon`, `xMoveToEx`, `xPeekMessage`, `xPostQuitMessage`, `xRectangle`,
    `xRegisterClassEx`, `xReleaseCapture`, `xReleaseDC`, `xRoundRect`, `xRtlGetVersion`, `xScreenToClient`, `xSelectClipRgn`,
    `xSelectObject`, `xSendMessage`, `xSetBkColor`, `xSetBkMode`, `xSetCapture`, `xSetCursor`, `xSetFocus`, `xSetParent`,
    `xSetPixelV`, `xSetTextColor`, `xSetTimer`, `xSetWindowLong`, `xSetWindowPlacement`, `xSetWindowPos`, `xSetWindowText`,
    `xShowWindow`, `xTrackMouseEvent`, `xTransparentBlt`, `xTranslateMessage`, `xUpdateWindow`, `idPOINT`, `idMESSAGE`, `idRECT`,
    `idSIZE`, `idPAINTSTRUCT`, `idBITMAPINFOHEADER`, `idBITMAPV5HEADER`, `idLOGFONT`, `idLOGBRUSH`, `idMINMAXINFO`,
    `idOSVERSIONINFO`, `idTRACKMOUSEEVENT`, `idWINDOWPLACEMENT`, `idWNDCLASSEX`, `ARROW_CURSOR`, `WINDOWS_VERSION`,
    `DEVCAP_LOGPIXELSY`, `js_re_am`, `js_re_sp`, `NullBrushID`, `pGdkGeometry`, `pLOGBRUSH`, `pLOGFONT`, `pMSG`, `pOSVERSIONINFO`,
    `pPAINTSTRUCT`, `pPOINT`, `pRECT`, `pSIZE`, `pTRACKMOUSEEVENT`, `pWINDOWPLACEMENT`, `pWNDCLASSEX`, `pW`, `pH`, `pX`, `pY`,
    `szAppName`, `tg_getID`, `CMAX`, `c_log`, `c_next`, `DF_NONE`, `DF_SIZE_API`, `DF_SET_XY`, `DF_SET_WH`, `DF_SET_NORM`,
    `DF_SET_USER`, `DF_SB_INFO`, `DF_FLAGS`, `DF_ACTIVE`, `dump_ctrls_on_resize`, `nodump`, `g_log`, `g_func`, `g_proc`, `g_funk`,
    `c_funk`, `c_funz`, `gtk_version`, `tg_to_bool`, `tg_to_int`, `tg_intint`, `tg_get_dialog_decoration_size`,
    `tg_get_window_rect`, `tg_WinAPI_getDC0`, `ccoDC`, `ccrDC`, `ReleaseDC0`, `tg_WinAPI_CreateCompatibleDC`, `gp_dstDC`,
    `gp_srcDC`, `tg_WinAPI_GetDestDC`, `tg_WinAPI_GetSrcDC`, `ufontwarn`, `font_cache`, `cached_fonts`, `cached_font_names`,
    `tg_set_font`, `tg_get_inherited_flag`, `tg_get_margins`, `tg_Init`, `hsv_to_rgba`, `tg_WinAPI_rgb_to_bgr`,
    `tg_GTK_rgba_to_bgra`, `tg_XPM_from_shorthand`, `tg_winAPI_create_DIB`, `tg_winAPI_create_DIB_from_xpm`,
    `tg_get_colour_table`, `tg_xpm_callback`, `xpm_texts`, `xpm_clrs`, `tg_WinAPI_replace_bgclr`, `xpm_image_slot`,
    `gPixbuf_from_Image`, `xImage_from_XPM`, `gGreyscale`, `tg_GTK_get_image_text_height`, `tg_WINAPI_get_image_text_height`,
    `tg_JS_get_image_height`, `tg_GTK_get_image_text_width`, `tg_gtk_get_layout`, `tg_gtk_mnemonicalize`, `tg_demnemonicalize`,
    `tg_gte_image_cache`, `tg_register_handler`, `tg_canvas_edge`, `ngroups`, `nflags`, `tg_lm_apply_normalisation`, `gNormalise`,
    `gNormalize`, `tg_lm_just_copy_concrete_sizes`, `tg_lm_accumulate_sizes`, `tg_lm_apply_space`,
    `tg_lm_accumulate_and_disperse_user_sizes`, `compact_string`, `bDumpMargins`, `bShowBGCLR`, `tg_lm_dump_ctrls`,
    `tg_resize_for_splitter`, `bDumpOnRedraw`, `tg_defer_attr`, `tg_gtk_set_cursor`, `tg_gtk_set_minmax`,
    `tg_apply_deferred_attributes`, `tg_collect_child_handlers`, `gGetInheritedHandler`, `gHide`, `tg_gtk_quit`, `key_map`,
    `tg_map_key`, `focus_id`, `brushColours`, `brushes`, `tg_WinAPI_get_brush`, `tg_fill_image`, `shiftkey`, `ctrlkey`, `altkey`,
    `tg_get_shiftkey`, `tg_get_altkey`, `hit_test`, `tg_get_mouse_on_scrollbar`, `tg_button_clicked`, `ONEDAY`, `SEVENDAYS`,
    `bGregorian`, `tg_last_day_of_month`, `tg_clamp_calendar`, `tg_calendar_set_hoverable`, `tg_save_calendar`,
    `tg_calendar_scroll`, `tg_calendar_mousemove`, `tg_calendar_recalculate_hover`, `tg_calendar_key`, `tg_calendar_mousewheel`,
    `tg_list_set_top_line`, `tg_list_set_line_col`, `tg_list_set_selection`, `tg_reactivate_caret`, `tg_list_key`,
    `tg_close_handler`, `TG_MENUITEM_HEIGHT`, `TG_MENU_FONT`, `TG_MENU_KEY_FONT`, `tg_get_menu_owner`, `tg_menu_redraw`,
    `tg_compute_menu_size`, `tg_build_menu`, `tg_draw_menu`, `tg_find_menu`, `tg_GTK_menu_draw`, `tg_GTK_expose_event`,
    `tg_get_menu_root`, `tg_menu_hit_test`, `tg_menu_visible`, `tg_hide_one_menu`, `tg_top_position`, `screen_width`,
    `screen_height`, `tg_get_screensize`, `tg_adjust_menu_pos`, `tg_ensure_popup`, `tg_show_menu`, `tg_open_child_menu`,
    `tg_hide_submenus`, `tg_hide_up`, `tg_hide`, `tg_gtk_kill_menu`, `tg_clear_and_set_radio_group`, `tg_call_menu_handler`,
    `tg_menu_mousemove`, `tg_GTK_menu_mousemove`, `tg_menu_leftclick`, `tg_GTK_menu_click`, `tg_menu_leave`, `tg_GTK_menu_leave`,
    `tg_next_enabled`, `tg_process_menu_keydown`, `PopMenuWndProc_cb`, `bPopMenuWndProcRegistered`, `tg_menubar_showtop`,
    `tg_menubar_click`, `tg_WINAPI_register_popup_class`, `tg_gtk_signal_connect`, `tg_get_mousepos`, `tg_scrollbar_key_handler`,
    `TMON`, `TKEY`, `TCTRL`, `tg_scrollbar_timer_action`, `tg_mousewheel`, `radio_sets`, `radio_selected`, `tg_chk_key`,
    `tg_tabs_get_tabset`, `tg_tab_change`, `tg_has_mnemonic`, `tg_process_mnemonics`, `tg_key_handler`, `tg_gtk_press`,
    `tg_gtk_press_key`, `tg_gtk_release_key`, `tg_track_mouseleave`, `tg_mouseleave`, `tg_scrollbar_mousemove`, `tg_list_hover`,
    `tg_table_transfer_actcols_to_columns`, `tg_table_change_hover`, `tg_table_mousemove`, `tg_mousemove_handler`,
    `tg_gtk_mousemove`, `tg_gtk_configure_event`, `tg_gtk_focusinout`, `gGetBrother`, `gGetChildCount`,
    `tg_tab_to_next_valid_control`, `tg_find_next_tab_stop`, `tg_WinAPI_process_key`, `tg_WinAPI_handles_match`, `tg_copy_image`,
    `tg_gtk_set_image_pen`, `tg_gtk_get_cairo`, `tg_gtk_rect`, `tg_gtk_timer_proc`, `tg_gtk_timer_proc_cb`,
    `tg_scrollbar_timer_cb`, `tg_scrollbar_click`, `tg_click_handler`, `xm`, `ym`, `tg_WinAPI_MOUSEMOVE`, `WINAPI_PENS`,
    `kill_pen`, `tg_WinAPI_get_pen`, `gDrawPixel`, `gGetPixel`, `imageDC`, `rL`, `gL`, `bL`, `pbw`, `pbh`, `tg_wu_set_rgbL`,
    `tg_plot`, `tg_plot2`, `fpart`, `tg_wu_line`, `tg_polyfill`, `plot_aa`, `tg_wu_ellipse`, `tg_wu_bezier`, `ellipse_point`,
    `tg_shifta`, `SBC_BACK`, `SBC_ARROWS`, `SBC_MONARB`, `SBC_THUMB`, `SBC_THUMBDRAG`, `SBC_THUMBHOV`, `SBC_SCROLLHOV`,
    `SBC_THMB`, `SBC_SOFT`, `ab_uldr`, `tg_get_scroll_arrows`, `tg_redraw_scrollbars`, `tg_redraw_canvas`,
    `tg_draw_control_images`, `tg_draw_dialog`, `tg_WinAPI_BUTTONDOWN`, `tg_WINAPI_mousewheel`, `assume_id`, `assumed_hWnd`,
    `tg_WinAPI_WndProc`, `tg_unit_tests`, `idle_rtn`, `idle_args`, `gtk_idle_id`, `idle_low`, `idle_stack`, `idle_params`,
    `low_priorities`, `hg_pop_or_prioritise_idle_stack`, `gtk_idle_func`, `gtk_idle_func_cb`, `tg_popup`, `tg_hsplit_get_size`,
    `tg_hsplit_save_size`, `crash_hat`, `TG_LEX_TK_END`, `TG_LEX_TK_SET`, `TG_LEX_TK_COMMA`, `TG_LEX_TK_NAME`, `TG_LEX_TK_HEX`,
    `tg_parse_attributes`, `dword_seq`, `paranormalise_traa`, `paranormalise_raa`, `paranormalise_draa`, `paranormalise_taa`,
    `paranormalise_vaa`, `paranormalise_ptaab`, `timer_ids`, `tg_WinAPI_timer_proc`, `tg_WinAPI_timer_proc_cb`,
    `tg_set_timer_attribute`, `tg_get_timer_attribute`, `tg_gtk_focus`, `tg_gtk_hide`, `tg_gtk_delete`, `tg_gtk_state_event`,
    `tg_gtk_dialog_draw`, `tg_gtk_scroll`, `tg_gtk_mouseleave`, `tg_gtk_grab_broken`, `tg_gtk_click`, `tg_setID`,
    `tg_WinAPI_create_control`, `tg_Dialog`, `tg_set_dialog_attribute`, `tg_get_dialog_attribute`, `tg_set_box_attribute`,
    `tg_get_box_attribute`, `gBox`, `gCbox`, `tg_list_cursorblink_action`, `tg_set_canvas_attribute`, `tg_set_button_attribute`,
    `tg_get_button_attribute`, `tg_btn_redraw`, `tg_btn_mouse_click`, `tg_btn_mouse_move`, `tg_btn_mouse_leave`,
    `tg_btn_un_hover`, `tg_btn_key`, `tg_chk_mouse_click`, `ucb`, `ccb`, `urb`, `crb`, `irb`, `tg_chk_redraw`,
    `tg_set_checkbox_attribute`, `tg_get_checkbox_attribute`, `tg_greyscale`, `cal_left`, `cal_lefth`, `cal_lefti`, `cal_right`,
    `cal_righth`, `cal_righti`, `tg_redraw_calendar`, `tg_calendar_mouseleave`, `tg_calendar_click`, `tg_set_calendar_attribute`,
    `tg_get_calendar_attribute`, `gCalendar`, `tg_draw_minor_ticks`, `tg_redraw_graph`, `tg_set_graph_attribute`,
    `tg_get_graph_attribute`, `tg_lbl_redraw`, `tg_list_get_data_length`, `tg_ensure_visible`, `tg_redraw_list`, `tg_list_click`,
    `tg_list_mouseleave`, `tg_set_list_attribute`, `tg_get_list_attribute`, `tg_find_menu_id`, `gMenuToggleInt`, `menu_images`,
    `tg_draw_one_menu`, `tg_draw_menubar`, `tg_menubar_mousemove`, `tg_menubar_mouseleave`, `tg_find_popup`, `tg_GTK_popup_draw`,
    `tg_GTK_popup_expose`, `tg_GTK_popup_click`, `tg_popup_leave`, `tg_GTK_popup_leave`, `PopupWndProc_cb`,
    `bPopupWndProcRegistered`, `stripes`, `tg_redraw_progressbar`, `tg_progress_action`, `tg_set_progressbar_attribute`,
    `tg_get_progressbar_attribute`, `slider_thumb`, `slider_vthumb`, `tg_draw_slider`, `tg_slider_mousemove`, `tg_slider_click`,
    `tg_set_slider_attribute`, `tg_get_slider_attribute`, `tg_draw_sizer`, `tg_splitter_mousemove`, `tg_splitter_click`,
    `tg_crop_text`, `tg_table_sum_to_col`, `tg_redraw_table`, `tg_table_mouseleave`, `tg_table_set_top_line`,
    `tg_table_ensure_visible`, `tg_table_ensure_line_visible`, `tg_table_ensure_col_visible`, `tg_table_column_sort`,
    `tg_table_set_tagsets`, `tg_table_set_selection`, `tg_table_click`, `tg_table_key`, `tg_set_table_attribute`,
    `tg_get_table_attribute`, `ximg`, `ltab`, `rtab`, `TAB_BORDER`, `TAB_BGCLR`, `TAB_BG_SEL`, `TAB_BG_NS`, `TAB_BG_HOV`,
    `TAB_OVER_HOV`, `tg_tabs_redraw`, `tg_tabs_mousemoveleave`, `tg_tabs_click`, `tg_tabs_key_handler`, `tg_set_tabs_attribute`,
    `tg_get_tabs_attribute`, `tg_nearest_cpos`, `tg_gtext_prev_word_boundary`, `tg_gtext_next_word_boundary`,
    `tg_text_process_mouseclickmove`, `date_pick_icon`, `tg_gtext_redraw`, `tg_gtext_cursorblink_action`, `TG_GTEXT_DEL`,
    `TG_GTEXT_SAME`, `TG_GTEXT_INS`, `TG_GTEXT_CPLX`, `tg_gtext_onediff`, `upos`, `tg_gtext_update_undo`, `tg_gtext_key_handler`,
    `gtext_menu`, `TG_GTEXT_POPUP_MENU`, `tg_gtext_menu_handler`, `tg_gtext_click`, `tg_gtext_mousemove`, `tg_gtext_mouseleave`,
    `tg_set_text_attribute`, `tg_get_text_attribute`, `TG_TREE_TEXT`, `TG_TREE_CHILDREN`, `TG_TREE_PARENT`, `TG_TREE_WIDTH`,
    `TG_TREE_CHECKED`, `TG_TREE_IMAGE`, `TG_TREE_USERDATA`, `TG_TREE_EXPANDED`, `TG_TREE_WIDEST`, `TG_TREE_VNC`, `tg_tree_n2d`,
    `tg_tree_d2n`, `tg_tree_get_display_code`, `tg_tree_vnc`, `tree_imgs`, `tucb`, `tccb`, `Cimg`, `Oimg`, `Dimg`, `TGTDL_TEXT`,
    `TGTDL_EXPANDED`, `TGTDL_CHECKED`, `TGTDL_IMAGE`, `TGTDL_USERDATA`, `TGTDL_CHILDREN`, `tg_tree_convert_nested_to_flat`,
    `tg_tree_defer_load`, `tg_tree_ec`, `tg_tree_collapse_node`, `tg_tree_expand_node`, `tg_tree_get_width`,
    `tg_leaf_or_collapsed_or_widest`, `tg_tree_get_widest`, `tg_redraw_tree`, `tg_tree_click`, `tg_tree_hover`,
    `tg_tree_mouseleave`, `tg_tree_key_handler`, `tg_set_tree_attribute`, `tg_get_tree_attribute`, `gTree`, `tg_placement`,
    `tg_gtk_gslist_to_strings`, `tg_unit_test`}},
  {}},
 {`pmaths.e`,
  {{}},
  {{}},
  {{`abs`, {{`a`, `?`}}},
   {`atan2`, {{`y`, `?`}, {`x`, `?`}}},
   {`bankers_rounding`, {{`pence`, `?`}, {`precision`, `1`}}},
   {`ceil`, {{`o`, `?`}}},
   {`exp`, {{`a`, `?`}}},
   {`max`, {{`a`, `?`}, {`b`, `?`}}},
   {`maxsq`, {{`s`, `?`}, {`return_index`, `false`}, {`exclude`, `0`}}},
   {`median`, {{`s`, `?`}}},
   {`min`, {{`a`, `?`}, {`b`, `?`}}},
   {`minsq`, {{`s`, `?`}, {`return_index`, `false`}, {`exclude`, `0`}}},
   {`mod`, {{`x`, `?`}, {`y`, `?`}}},
   {`mulmod`, {{`a`, `?`}, {`b`, `?`}, {`modulus`, `?`}}},
   {`powmod`, {{`base`, `?`}, {`exponent`, `?`}, {`modulus`, `?`}}},
   {`round`, {{`a`, `?`}, {`inverted_precision`, `1`}}},
   {`sign`, {{`a`, `?`}}},
   {`trunc`, {{`x`, `?`}}}}},
 {`porall.e`,
  {{}},
  {{}},
  {{`or_all`, {{`s`, `?`}}},
   {`or_allu`, {{`s`, `?`}}}}},
 {`ppp.e`,
  {{`find.e`, `ppp.e`}},
  {{`ppp_Maxlen`, `ppp_Indent`, `ppp_Nest`, `ppp_Pause`, `ppp_StrFmt`, `ppp_IntCh`, `ppp_Init`, `ppp_Ascii`, `ppp_IntFmt`,
    `ppp_FltFmt`, `ppp_Date`, `ppp_Br`, `ppp_Q22`, `ascii`, `ppp_File`, `ppp_result`, `pline`, `plen`, `sline`, `nindent`,
    `spurge`, `sput`, `escBytes`, `escChars`, `constants`, `graphic`, `cl1q`, `cllq`, `prnf`, `setAscii`, `pp_Init`, `setOpt`,
    `pp_Ex`}},
  {{`pp`, {{`o`, `?`}, {`options`, `{}`}}},
   {`ppEx`, {{`o`, `?`}, {`options`, `?`}}},
   {`ppExf`, {{`o`, `?`}, {`options`, `?`}}},
   {`ppf`, {{`o`, `?`}, {`options`, `{}`}}},
   {`ppOpt`, {{`options`, `?`}}}}},
 {`pqueue.e`,
  {{}},
  {{`q`, `pq`, `PDATA`, `PRIORITY`, `pqinit`, `pqtype`, `pqcrid`, `freelist`, `pq_compare`, `pq_init`, `q_init`, `qtypes`,
    `qfreelist`}},
  {{`destroy_queue`, {{`qid`, `?`}}},
   {`new_queue`, {{`qtype`, `FIFO_QUEUE`}}},
   {`new_stack`, {{`qtype`, `LIFO_QUEUE`}}},
   {`peep`, {{`qid`, `?`}, {`n`, `-1`}, {`qtype`, `ANY_QUEUE`}}},
   {`peepn`, {{`qid`, `?`}, {`n`, `?`}, {`qtype`, `ANY_QUEUE`}}},
   {`pop`, {{`qid`, `?`}, {`n`, `-1`}, {`qtype`, `ANY_QUEUE`}, {`bPop`, `true`}}},
   {`popn`, {{`qid`, `?`}, {`n`, `?`}, {`qtype`, `ANY_QUEUE`}}},
   {`pq_add`, {{`item`, `?`}, {`pqid`, `1`}}},
   {`pq_destroy`, {{`pqid`, `1`}, {`justclear`, `false`}, {`crid`, `-2`}}},
   {`pq_empty`, {{`pqid`, `1`}}},
   {`pq_new`, {{`t`, `MIN_HEAP`}, {`crid`, `-2`}}},
   {`pq_peek`, {{`pqid`, `1`}}},
   {`pq_pop`, {{`pqid`, `1`}}},
   {`pq_pop_data`, {{`pqid`, `1`}}},
   {`pq_size`, {{`pqid`, `1`}}},
   {`push`, {{`qid`, `?`}, {`item`, `?`}, {`bSingle`, `true`}}},
   {`pushn`, {{`qid`, `?`}, {`items`, `?`}}},
   {`queue_empty`, {{`qid`, `?`}}},
   {`queue_size`, {{`qid`, `?`}}}}},
 {`premoveall.e`,
  {{`find.e`}},
  {{}},
  {{`remove_all`, {{`needle`, `?`}, {`haystack`, `?`}}}}},
 {`primes.e`,
  {{`bsearch.e`, `pfactors.e`, `pmaths.e`, `primes.e`}},
  {{`primes`, `sieved`, `init_sieve`, `add_block`}},
  {{`get_maxprime`, {{`m`, `?`}}},
   {`get_prime`, {{`k`, `?`}}},
   {`get_primes`, {{`count`, `0`}}},
   {`get_primes_le`, {{`hi`, `?`}, {`overrun`, `0`}}},
   {`is_prime`, {{`n`, `?`}, {`bIndex`, `-1`}}}}},
 {`pseqc.e`,
  {{`pmaths.e`}},
  {{}},
  {{`head`, {{`src`, `?`}, {`size`, `1`}}},
   {`insert`, {{`src`, `?`}, {`what`, `?`}, {`index`, `?`}}},
   {`pad`, {{`src`, `?`}, {`size`, `?`}, {`method`, `"BOTH"`}, {`ch`, `0X20`}}},
   {`pad_head`, {{`src`, `?`}, {`size`, `?`}, {`ch`, `0X20`}}},
   {`pad_tail`, {{`src`, `?`}, {`size`, `?`}, {`ch`, `0X20`}}},
   {`remove`, {{`src`, `?`}, {`start`, `?`}, {`stop`, `start`}}},
   {`replace`, {{`src`, `?`}, {`replacement`, `?`}, {`start`, `?`}, {`stop`, `start`}}},
   {`splice`, {{`src`, `?`}, {`what`, `?`}, {`index`, `?`}}},
   {`tail`, {{`src`, `?`}, {`size`, `-1`}}},
   {`valid_index`, {{`s`, `?`}, {`idx`, `?`}}}}},
 {`pseries.e`,
  {{`psqop.e`}},
  {{`binop_ok`}},
  {{`series`, {{`start`, `?`}, {`increment`, `?`}, {`count`, `2`}, {`op`, `0X2B`}}}}},
 {`psmall.e`,
  {{}},
  {{}},
  {}},
 {`psplit.e`,
  {{`find.e`, `match.e`, `pfindany.e`}},
  {{}},
  {{`split`, {{`source`, `?`}, {`delimiter`, `0X20`}, {`no_empty`, `true`}, {`limit`, `0`}}},
   {`split_any`, {{`source`, `?`}, {`delimiters`, `", \t|"`}}},
   {`split_by`, {{`s`, `?`}, {`n`, `?`}}},
   {`split_path`, {{`path`, `?`}, {`preservetrailsep`, `false`}}}}},
 {`psqop.e`,
  {{`log10.e`, `misc.e`, `pmaths.e`, `psqop.e`}},
  {{`sq_fatal`, `sq_general`, `sq_unary`, `sq_ln`}},
  {{`sq_abs`, {{`a`, `?`}}},
   {`sq_add`, {{`a`, `?`}, {`b`, `?`}}},
   {`sq_and`, {{`a`, `?`}, {`b`, `?`}}},
   {`sq_and_bits`, {{`a`, `?`}, {`b`, `?`}}},
   {`sq_arccos`, {{`a`, `?`}}},
   {`sq_arcsin`, {{`a`, `?`}}},
   {`sq_arctan`, {{`a`, `?`}}},
   {`sq_atom`, {{`a`, `?`}}},
   {`sq_ceil`, {{`a`, `?`}}},
   {`sq_cmp`, {{`a`, `?`}, {`b`, `?`}}},
   {`sq_cos`, {{`a`, `?`}}},
   {`sq_div`, {{`a`, `?`}, {`b`, `?`}}},
   {`sq_even`, {{`a`, `?`}}},
   {`sq_eq`, {{`a`, `?`}, {`b`, `?`}}},
   {`sq_floor`, {{`a`, `?`}}},
   {`sq_floor_div`, {{`a`, `?`}, {`b`, `?`}}},
   {`sq_ge`, {{`a`, `?`}, {`b`, `?`}}},
   {`sq_gt`, {{`a`, `?`}, {`b`, `?`}}},
   {`sq_int`, {{`a`, `?`}}},
   {`sq_le`, {{`a`, `?`}, {`b`, `?`}}},
   {`sq_log`, {{`a`, `?`}}},
   {`sq_log10`, {{`a`, `?`}}},
   {`sq_log2`, {{`a`, `?`}}},
   {`sq_lt`, {{`a`, `?`}, {`b`, `?`}}},
   {`sq_max`, {{`a`, `?`}, {`b`, `?`}}},
   {`sq_min`, {{`a`, `?`}, {`b`, `?`}}},
   {`sq_mod`, {{`a`, `?`}, {`b`, `?`}}},
   {`sq_mul`, {{`a`, `?`}, {`b`, `?`}}},
   {`sq_ne`, {{`a`, `?`}, {`b`, `?`}}},
   {`sq_not`, {{`a`, `?`}}},
   {`sq_not_bits`, {{`a`, `?`}}},
   {`sq_odd`, {{`a`, `?`}}},
   {`sq_or`, {{`a`, `?`}, {`b`, `?`}}},
   {`sq_or_bits`, {{`a`, `?`}, {`b`, `?`}}},
   {`sq_power`, {{`a`, `?`}, {`b`, `?`}}},
   {`sq_rand`, {{`a`, `?`}}},
   {`sq_rmdr`, {{`a`, `?`}, {`b`, `?`}}},
   {`sq_round`, {{`a`, `?`}, {`inverted_precision`, `1`}}},
   {`sq_seq`, {{`a`, `?`}}},
   {`sq_sign`, {{`a`, `?`}}},
   {`sq_sin`, {{`a`, `?`}}},
   {`sq_sqrt`, {{`a`, `?`}}},
   {`sq_str`, {{`a`, `?`}}},
   {`sq_sub`, {{`a`, `?`}, {`b`, `?`}}},
   {`sq_tan`, {{`a`, `?`}}},
   {`sq_trunc`, {{`a`, `?`}}},
   {`sq_uminus`, {{`a`, `?`}}},
   {`sq_xor`, {{`a`, `?`}, {`b`, `?`}}},
   {`sq_xor_bits`, {{`a`, `?`}, {`b`, `?`}}}}},
 {`psum.e`,
  {{}},
  {{`zl`, `std_dev`}},
  {{`average`, {{`a`, `?`}, {`zlr`, `0`}}},
   {`product`, {{`a`, `?`}, {`zlr`, `1`}}},
   {`sum`, {{`a`, `?`}, {`zlr`, `0`}}},
   {`std_dev`, {{`a`, `?`}, {`zlr`, `0`}}}}},
 {`ptagset.e`,
  {{`pmaths.e`, `ptagset.e`}},
  {{}},
  {{`tagset`, {{`lim`, `?`}, {`start`, `1`}, {`step`, `1`}}},
   {`tagstart`, {{`start`, `?`}, {`len`, `?`}, {`step`, `1`}}}}},
 {`ptrim.e`,
  {{`find.e`, `psqop.e`, `psum.e`, `ptrim.e`}},
  {{}},
  {{`shorten`, {{`s`, `?`}, {`what`, `"digits"`}, {`ml`, `20`}, {`fmt`, `""`}}},
   {`trim`, {{`source`, `?`}, {`what`, `" \t\r\n"`}, {`return_index`, `false`}}},
   {`trim_head`, {{`source`, `?`}, {`what`, `" \t\r\n"`}, {`return_index`, `false`}}},
   {`trim_tail`, {{`source`, `?`}, {`what`, `" \t\r\n"`}, {`return_index`, `false`}}}}},
 {`punique.e`,
  {{`dict.e`, `punique.e`, `sort.e`}},
  {{`RD_INPLACE`, `RD_PRESORTED`, `RD_SORT`, `ops`, `remove_dups`}},
  {{`unique`, {{`s`, `?`}, {`options`, `"SORT"`}}}}},
 {`pvlookup.e`,
  {{`find.e`, `match.e`, `pcase.e`, `ppp.e`, `ptrim.e`}},
  {{`lookup`, `keyvalues`, `text_format`}},
  {{`vlookup`, {{`find_item`, `?`}, {`grid_data`, `?`}, {`source_col`, `?`}, {`target_col`, `?`}, {`def_value`, `0`}}}}},
 {`scanf.e`,
  {{`find.e`, `match.e`, `pcase.e`}},
  {{`NONE`, `LITERAL`, `ATOM`, `STRING`, `DECIMAL`, `BINARY`, `HEXADEC`, `OCTAL`, `ROMAN`, `ROMAL`, `parse_fmt`, `scan_ch`,
    `baseset`, `bases`, `binit`, `initb`, `completeFloat`, `get_number`, `from_roman`, `get_roman`, `scanff`}},
  {{`scanf`, {{`s`, `?`}, {`fmt`, `?`}}},
   {`to_number`, {{`s`, `?`}, {`failure`, `{}`}, {`inbase`, `10`}}}}},
 {`shift_bits.e`,
  {{}},
  {{}},
  {{`count_bits`, {{`n`, `?`}, {`nFrames`, `2`}}},
   {`shift_bits`, {{`n`, `?`}, {`shift_distance`, `?`}}}}},
 {`shuffle.e`,
  {{}},
  {{}},
  {{`shuffle`, {{`s`, `?`}}}}},
 {`sort.e`,
  {{}},
  {{`tagsort`, `column_compare`}},
  {{`custom_sort`, {{`custom_compare`, `?`}, {`x`, `?`}, {`data`, `{}`}, {`order`, `ASCENDING`}}},
   {`sort`, {{`x`, `?`}, {`order`, `ASCENDING`}}},
   {`sort_columns`, {{`x`, `?`}, {`column_list`, `?`}}}}},
 {`speak.e`,
  {{}},
  {{}},
  {{`speak`, {{`text`, `?`}, {`rate`, `0`}, {`speech_cb`, `0`}}}}},
 {`substitute.e`,
  {{`match.e`, `substitute.e`}},
  {{}},
  {{`substitute`, {{`text`, `?`}, {`s`, `?`}, {`r`, `?`}, {`limit`, `-1`}}},
   {`substitute_all`, {{`text`, `?`}, {`strings`, `?`}, {`replacements`, `?`}}}}},
 {`timedate.e`,
  {{`find.e`, `pcase.e`, `pcolumn.e`, `pdates.e`, `pmaths.e`}},
  {{`DT_TZ`, `DT_DSTZ`, `DSTrule`, `addDSTrule`, `EU`, `US`, `AU`, `tdaDD`, `timezones`, `tzdescs`, `tzadjs`, `tzDSR`, `tzDSL`,
    `ktz`, `alttzkeys`, `alttz`, `validtd`, `TD_LITERAL`, `YEAR`, `MONTH`, `DAY`, `DOW`, `DOY`, `HOUR`, `MINUTE`, `SECOND`,
    `MSEC`, `AM`, `TZ`, `TH`, `en`, `langmax`, `currlang`, `months`, `day_names`, `td_ordinals`, `ampm`, `isDSTr`, `get_DST_rule`,
    `timedate_to_julian_day`, `julian_day_to_timedate`, `DAY_IN_SECONDS`, `timedate_to_seconds`, `seconds_to_timedate`, `edescs`,
    `ecxtra`, `nxtch`, `next_fmt`, `to_space`, `td_get_number`, `get_any`, `parse_one`, `default_parse_fmts`, `allow_partial`,
    `default_format`}},
  {{`timedelta`,
    {{`weeks`, `0`}, {`days`, `0`}, {`hours`, `0`}, {`minutes`, `0`}, {`seconds`, `0`}, {`milliseconds`, `0`},
     {`microseconds`, `0`}}},
   {`get_tzid`, {{`tz`, `?`}}},
   {`override_timezone`, {{`tz`, `?`}, {`desc`, `?`}, {`adj`, `?`}, {`dsr`, `0`}, {`dst`, ``}}},
   {`adjust_timedate`, {{`td`, `?`}, {`delta`, `?`}}},
   {`set_timezone`, {{`td`, `?`}, {`newtz`, `?`}}},
   {`change_timezone`, {{`td`, `?`}, {`newtz`, `?`}}},
   {`set_timedate_formats`, {{`parse_fmts`, `?`}, {`out_fmt`, `1`}, {`partial`, `0`}}},
   {`parse_date_string`, {{`s`, `?`}, {`fmts`, `?`}, {`partial`, `?`}}},
   {`format_timedate`, {{`td`, `?`}, {`fmt`, `?`}}},
   {`timedate_diff`, {{`td1`, `?`}, {`td2`, `?`}, {`term`, `0`}}}}},
 {`to_int.e`,
  {{`pcase.e`, `to_int.e`}},
  {{}},
  {{`is_integer`, {{`s`, `?`}, {`base`, `10`}}},
   {`to_integer`, {{`s`, `?`}, {`def_value`, `0`}, {`base`, `10`}}}}},
 {`to_str.e`,
  {{`matchrepl.e`, `pseqc.e`, `ptrim.e`, `to_str.e`}},
  {{}},
  {{`to_string`, {{`data_in`, `?`}, {`string_quote`, `0`}, {`embed_string_quote`, `0X22`}}}}},
 {`unit_test.e`,
  {{`find.e`, `pFilter.e`, `pcase.e`, `pextract.e`, `pmaths.e`, `unit_test.e`}},
  {{`tests_run`, `tests_passed`, `tests_failed`, `verbosity`, `abort_on_fail`, `pause_summary`, `log_fn`, `module`, `prev_module`,
    `test_log`, `show_module`, `get_tests_failed`, `sn2`, `test_result`, `rec_equal`, `bool_or_string`}},
  {{`set_test_abort`, {{`abort_test`, `?`}}},
   {`set_test_logfile`, {{`filename`, `?`}}},
   {`set_test_module`, {{`name`, `?`}}},
   {`set_test_pause`, {{`pause`, `?`}}},
   {`set_test_verbosity`, {{`level`, `?`}}},
   {`test_equal`, {{`a`, `?`}, {`b`, `?`}, {`name`, `""`}, {`args`, `{}`}, {`bApprox`, `-1`}, {`eq`, `true`}}},
   {`test_fail`, {{`name`, `""`}, {`args`, `{}`}}},
   {`test_false`, {{`success`, `?`}, {`name`, `""`}, {`args`, `{}`}}},
   {`test_not_equal`, {{`a`, `?`}, {`b`, `?`}, {`name`, `""`}, {`args`, `{}`}, {`bApprox`, `false`}}},
   {`test_pass`, {{`name`, `""`}, {`args`, `{}`}}},
   {`test_summary`, {{`close_log`, `true`}}},
   {`test_true`, {{`success`, `?`}, {`name`, `""`}, {`args`, `{}`}}}}},
 {`unix_dict.e`,
  {{}},
  {{}},
  {{`unix_dict`, {{`minlen`, `0`}}}}},
 {`vslice.e`,
  {{}},
  {{}},
  {{`vslice`, {{`source`, `?`}, {`column`, `?`}, {`error_control`, `0`}}}}},
 {`wildcard.e`,
  {{`find.e`, `match.e`, `pcase.e`, `wildcard.e`}},
  {{`qmatch`, `END_MARKER`}},
  {{`wildcard_file`, {{`pattern`, `?`}, {`filename`, `?`}}},
   {`wildcard_match`, {{`pattern`, `?`}, {`str`, `?`}}}}}}


